apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-data
  namespace: daniel-lopez-fisag-dev
  labels:
    app: backend-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-data
  template:
    metadata:
      labels:
        app: backend-data
    spec:
      containers:
      - name: backend-data
        image: danielopezh/comments-backend-data:{{ tag }}
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: MONGO_URL
          value: "mongodb://database:27017/comments"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-data
  namespace: daniel-lopez-fisag-dev
  labels:
    app: backend-data
spec:
  selector:
    app: backend-data
  ports:
  - port: 80
    targetPort: 3001
